; ---------------------------------------------------------------------------
; - DISPLAY - Equates (equates.inc)                                         -
; - Copyright (C) 1998-2025 Alexandru Groza of Microprogramming TECHNIQUES  -
; - All rights reserved.                                                    -
; ---------------------------------------------------------------------------
; - License: GNU General Public License v3.0                                -
; ---------------------------------------------------------------------------

; general program equates
; ---------------------------------------------------------------------------
  kMaxFileSize           EQU  0F800h

; keyboard equates
; ---------------------------------------------------------------------------
  kKeyEscape             EQU  1Bh
  kKeyUp                 EQU  4800h
  kKeyDown               EQU  5000h
  kKeyPageUp             EQU  4900h
  kKeyPageDown           EQU  5100h
  kKeyHome               EQU  4700h
  kKeyEnd                EQU  4F00h
