; ---------------------------------------------------------------------------
; - DISPLAY - Variables (vars.inc)                                          -
; - Copyright (C) 1998-2025 Alexandru Groza of Microprogramming TECHNIQUES  -
; - All rights reserved.                                                    -
; ---------------------------------------------------------------------------
; - License: GNU General Public License v3.0                                -
; ---------------------------------------------------------------------------

; general program variables (including preinitialized)
; ---------------------------------------------------------------------------
  GFileHandle            DW   ?
  GFileSize              DW   ?
  GFileSize64KLimit      DB   0
  GSegmentAllocated      DW   ?
